name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: lvdianChatBotTest  # 设置为您的 Azure Web App 名称
  PYTHON_VERSION: '3.12'  # 设置要使用的 Python 版本

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest  # 如果您有测试，确保安装 pytest

      - name: Run tests
        run: |
          pytest  # 运行 pytest 测试

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Check deployment status
        run: curl -s ${{ secrets.AZURE_WEBAPP_URL }}/api/messages -o /dev/null -w "%{http_code}"

