import os
from flask import Flask, request, jsonify
import requests

app = Flask(__name__)

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_API_URL = os.getenv('OPENAI_API_URL')

@app.route('/api/messages', methods=['POST'])
def get_openai_response():
    user_message = request.json.get('message')
    response = requests.post(
        OPENAI_API_URL,
        headers={
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {OPENAI_API_KEY}'
        },
        json={
            'prompt': user_message,
            'max_tokens': 150
        }
    )

    bot_message = response.json()['choices'][0]['text'].strip()
    return jsonify({'message': bot_message})

if __name__ == '__main__':
    app.run(port=os.getenv('PORT', 5000))
